### ISSUE TITLE
Issue#3

### ISSUE THREAD

**Issue by ps-19** [ps-19/ps-19#3]

**Comment by Dhruvacube** [comment]
hey @ps-19 could you please give me your discord id I need to talk to you regarding the https://hackcbs4.hackerearth.com/ invitation , since I saw that you wanted to join my team :) 

## TBH Your Readme JS was just ☠️

**Comment by Rufaida98** [comment]
Hi @ps-19 sorry to bother you but i had an issue while adding an empty folder, can you tell me how you add the tutorial empty folder. I am new to github and i really want to learn. Thank you so much

**Comment by ps-19** [comment]
@Rufaida98 actually empty folder can not be added and pushed to the github. It will not consider while pushing to repository.

**Comment by Rufaida98** [comment]
@ps-19 so what should i do?.i did add it as a file though
